/// Application-wide configuration constants.
///
/// The developer MUST update [panelBaseUrl] and [backendBaseUrl] before
/// distributing the app.  These values are compiled into the binary — they
/// are NOT user-editable and should never contain admin API keys or other
/// admin secrets.
class AppConfig {
  AppConfig._();

  /// Base URL of the Remnawave panel (without trailing slash).
  ///
  /// Example: `'https://panel.example.com'`
  ///
  /// Set this to your panel URL before building the release APK/IPA.
  static const String panelBaseUrl = 'https://panel.ulya.space';

  /// Base URL of the Bedolaga backend (without trailing slash).
  ///
  /// Used by the mobile app to fetch the public server catalog when the user
  /// has no personal subscription URL yet.
  ///
  /// Example: `'https://bot.example.com'`
  ///
  /// Set this to your Bedolaga backend URL before building the release APK/IPA.
  static const String backendBaseUrl = 'https://api.ulya.space';

  /// Custom URL scheme used as OAuth callback target.
  /// Must match AndroidManifest CallbackActivity + Info.plist + the
  /// authorized redirect URI registered for the OAuth client in the Cabinet
  /// admin panel: `ulyavpn://oauth/callback`.
  static const String oauthScheme   = 'ulyavpn';
  static const String oauthCallback = 'ulyavpn://oauth/callback';

  /// Telegram OIDC client id (from @BotFather → Login Widget → Client ID).
  /// This is the OAuth/OIDC client id, NOT the bot's user id. Used as
  /// `client_id` in the authorization request; the backend validates the
  /// id_token's `aud` against it (`TELEGRAM_OIDC_CLIENT_ID`).
  static const String telegramOidcClientId = '8380612257';

  /// Telegram OIDC authorization endpoint (from the OpenID discovery doc
  /// `https://oauth.telegram.org/.well-known/openid-configuration`).
  static const String telegramAuthorizeEndpoint =
      'https://oauth.telegram.org/auth';

  /// Telegram Native Login App Link redirect URI. Auto-generated by @BotFather
  /// (`https://app{nativeAppId}-login.tg.dev/tglogin`) and verified against the
  /// release keystore SHA-256 registered there. Telegram redirects the
  /// authorization result to this https URL; because the domain is an Android
  /// App Link (autoVerify), the OS opens the app directly. Caught in Dart via
  /// the app_links package (see TelegramAuthLink). Must match BotFather exactly.
  static const String telegramAuthCallback =
      'https://app982852799-login.tg.dev/tglogin';

  /// Host portion of [telegramAuthCallback] — used to match the incoming App
  /// Link. Keep in sync with the AndroidManifest intent-filter.
  static const String telegramAuthCallbackHost = 'app982852799-login.tg.dev';

  /// Sentry DSN for crash reporting. Empty string disables Sentry entirely
  /// (no SDK init, zero network calls) — safe default for local dev builds.
  /// Create a Flutter project at sentry.io (or self-hosted) and paste the
  /// DSN here before building a release.
  static const String sentryDsn = '';

  /// Package names excluded from VPN tunnel by default (on first launch).
  static const List<String> defaultBlockedApps = [
    'com.vk.vkvideo',        // VK Video
    'com.vkontakte.android', // VK (старый)
    'ru.mail.mailapp',       // MAX (Mail.ru)
    'ru.rostel',             // Госуслуги (Новая)
    'ru.gosuslugi.mobile',   // Госуслуги

  ];
}
